In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [2]:
#load the dataset
data=pd.read_csv('Churn_Modelling (1).csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,NaN,1.0,79084.10,0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10002 non-null  int64
 1   CustomerId       10002 non-null  int64
 2   Surname          10002 non-null  object
 3   CreditScore      10002 non-null  int64
 4   Geography        10001 non-null  object
 5   Gender           10002 non-null  object
 6   Age              10001 non-null  float64
 7   Tenure           10002 non-null  int64
 8   Balance          10002 non-null  float64
 9   NumOfProducts    10002 non-null  int64
 10  HasCrCard        10001 non-null  float64
 11  IsActiveMember   10001 non-null  float64
 12  EstimatedSalary  10002 non-null  float64
 13  Exited           10002 non-null  int64
dtypes: float64(5), int64(6), object(3)
memory usage: 1.1+ MB

In [4]:
# Preprocess data
# drop irrelevant features or columns
data = data.drop(['RowNumber','CustomerId','Surname'],axis = 1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,608,Spain,Female,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,502,France,Female,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,699,France,Female,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,850,Spain,Female,43.0,2,125510.82,1,NaN,1.0,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9997,709,France,Female,36.0,7,0.00,1,0.0,1.0,42085.58,1
9998,772,Germany,Male,42.0,3,75075.31,2,1.0,0.0,92888.52,1
9999,772,Germany,Male,42.0,3,75075.31,2,1.0,0.0,92888.52,1
10000,792,France,Female,28.0,4,130142.79,1,1.0,0.0,38190.78,0
10001,792,France,Female,28.0,4,130142.79,1,1.0,0.0,38190.78,0

In [5]:
# Encode categorical values
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,608,Spain,0,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,502,France,0,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,699,France,0,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,850,Spain,0,43.0,2,125510.82,1,NaN,1.0,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9997,709,France,0,36.0,7,0.00,1,0.0,1.0,42085.58,1
9998,772,Germany,1,42.0,3,75075.31,2,1.0,0.0,92888.52,1
9999,772,Germany,1,42.0,3,75075.31,2,1.0,0.0,92888.52,1
10000,792,France,0,28.0,4,130142.79,1,1.0,0.0,38190.78,0
10001,792,France,0,28.0,4,130142.79,1,1.0,0.0,38190.78,0

In [6]:
data.isnull().sum()

CreditScore        0
Geography          1
Gender             0
Age                1
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          1
IsActiveMember     1
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
data['Geography'].unique()

array(['France', 'Spain', nan, 'Germany'], dtype=object)

In [8]:
data['Geography'].value_counts()

Geography
France     5014
Germany    2510
Spain      2477
Name: count, dtype: int64

In [9]:
data['HasCrCard'].value_counts()

HasCrCard
1.0    7056
0.0    2945
Name: count, dtype: int64

In [10]:
data['IsActiveMember'].value_counts()

IsActiveMember
1.0    5150
0.0    4851
Name: count, dtype: int64

In [11]:
data['Age'] = data['Age'].fillna(data['Age'].mean())
data['HasCrCard'] = data['HasCrCard'].fillna(1.0)
data['IsActiveMember'] = data['IsActiveMember'].fillna(1.0)
data['Geography'] = data['Geography'].fillna('France')

In [12]:
data.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [13]:
data.dropna(inplace = True)

In [14]:
# One hot encoder geography column
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<10002x3 sparse matrix of type '<class 'numpy.float64'>'
	with 10002 stored elements in Compressed Sparse Row format>

In [15]:
a = geo_encoder.toarray()

In [16]:
b = onehot_encoder_geo.get_feature_names_out(['Geography'])

In [17]:
geo_encoded_df = pd.DataFrame(a,columns=b)
geo_encoded_df

       Geography_France  Geography_Germany  Geography_Spain
0                   1.0                0.0              0.0
1                   0.0                0.0              1.0
2                   1.0                0.0              0.0
3                   1.0                0.0              0.0
4                   0.0                0.0              1.0
...                 ...                ...              ...
9997                1.0                0.0              0.0
9998                0.0                1.0              0.0
9999                0.0                1.0              0.0
10000               1.0                0.0              0.0
10001               1.0                0.0              0.0

[10002 rows x 3 columns]

In [18]:
# combine one hot encoder columns with the original data
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42.0,2,0.00,1,1.0,1.0,101348.88,1,1.0,0.0,0.0
1,608,0,41.0,1,83807.86,1,0.0,1.0,112542.58,0,0.0,0.0,1.0
2,502,0,42.0,8,159660.80,3,1.0,0.0,113931.57,1,1.0,0.0,0.0
3,699,0,39.0,1,0.00,2,0.0,0.0,93826.63,0,1.0,0.0,0.0
4,850,0,43.0,2,125510.82,1,1.0,1.0,79084.10,0,0.0,0.0,1.0

In [19]:
# Save the encoders and scaler
with open('label_encoder_gender.pk1','wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pk1','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [20]:
# Divide the dataset int independent(i/p) and dependent(o/p) features:
x = data.drop('Exited', axis=1)
y = data['Exited']

# split the data in training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

# scale these features:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [21]:
with open('scaler.pk1','wb') as file:
    pickle.dump(scaler, file)

In [22]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping
import datetime

In [23]:
# Build our ANN model
model = Sequential([
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

In [24]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.compile(optimizer='adam', loss="binary_crossentropy", metrics=['accuracy'])

In [26]:
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [27]:
history = model.fit(x_train, y_train, validation_data=(x_test,y_test), epochs=100, callbacks=[early_stopping_callback])

Epoch 1/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.8003 - loss: 0.4836 - val_accuracy: 0.8391 - val_loss: 0.3887
Epoch 2/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8364 - loss: 0.3931 - val_accuracy: 0.8526 - val_loss: 0.3644
Epoch 3/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8507 - loss: 0.3577 - val_accuracy: 0.8626 - val_loss: 0.3515
Epoch 4/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.8537 - loss: 0.3494 - val_accuracy: 0.8601 - val_loss: 0.3480
Epoch 5/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8539 - loss: 0.3484 - val_accuracy: 0.8581 - val_loss: 0.3541
Epoch 6/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8631 - loss: 0.3307 - val_accuracy: 0.8641 - val_loss: 0.3491
Epoch 7/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8659 - loss: 0.3254 - val_accuracy: 0.8596 - val_loss: 0.3514
Epoch 8/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.8652 - loss: 0.3275 - val_accuracy: 0.8596 - val_loss: 0.3486
Epoch 9/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8619 - loss: 0.3397 - val_accuracy: 0.8611 - val_loss: 0.3449
Epoch 10/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8611 - loss: 0.3380 - val_accuracy: 0.8621 - val_loss: 0.3432
Epoch 11/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.8639 - loss: 0.3202 - val_accuracy: 0.8606 - val_loss: 0.3458
Epoch 12/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8658 - loss: 0.3249 - val_accuracy: 0.8601 - val_loss: 0.3443
Epoch 13/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8691 - loss: 0.3169 - val_accuracy: 0.8631 - val_loss: 0.3397
Epoch 14/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8738 - loss: 0.3045 - val_accuracy: 0.8646 - val_loss: 0.3451
Epoch 15/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8629 - loss: 0.3244 - val_accuracy: 0.8616 - val_loss: 0.3419
Epoch 16/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8676 - loss: 0.3193 - val_accuracy: 0.8656 - val_loss: 0.3420
Epoch 17/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8655 - loss: 0.3195 - val_accuracy: 0.8621 - val_loss: 0.3493
Epoch 18/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8633 - loss: 0.3324 - val_accuracy: 0.8626 - val_loss: 0.3460

In [28]:
# save the model file
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.